#spring.datasource.url=jdbc:mysql://localhost:3306/bjpost?serverTimezone=UTC&characterEncoding=UTF-8
#
## DB username
#spring.datasource.username=root
## DB password
#spring.datasource.password=Joong1001!
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bjpost?characterEncoding=UTF-8
    username: root
    password: Joong1001!

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
