## ???? DB URL(?? ?? ??)
#spring.datasource.url=jdbc:mysql://${rds_endpoint}:${rds.port}/${rds.schema}?characterEncoding=UTF-8
#spring.datasource.username=${rds_username}
#spring.datasource.password=${rds_password}
#
#
#spring.jpa.properties.hibernate.format_sql:true
#spring.jpa.properties.hibernate.jdbc:time_zone: Asia/Seoul
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
## ???? ?? ?? ??
#spring.jpa.hibernate.ddl-auto=none

spring:
  datasource:
    url: jdbc:mysql://${rds.endpoint}:${rds.port}/${rds.schema}?characterEncoding=UTF-8
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace