name: bjpost   # 깃허브 액션에 표시되는 이 workflow의 이름

# 트리거(언제 이 워크플로우가 실행될지 설정)
on:
  push:
    branches:
      - main # (1) 트리거 브랜치 설정: 해당 브랜치에 push되면 스크립트 실행됨
  workflow_dispatch: # (2) 수동 실행: main 브랜치 push외에도 수동으로 해당 스크립트를 실행가능하도록 한다.
defaults:
  run:
    working-directory: . # 해당 디렉토리 하위에 gradlew가 존재하므로 시작 디렉토리를 조정한다.
jobs:
  build:
    runs-on: ubuntu-latest # (3) Github Action 스크립트가 작동될 OS 환경 지정

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # (4) 프로젝트 코드 체크아웃

      - name: Set up JDK 17
        uses: actions/setup-java@v1 # (5)  GitHub Action이 실행될 OS에 Java 설치
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # (6) gradle wrapper를 실행할 수 있도록 실행권한 줌
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # (7) gradle wrapper를 통해 해당 프로젝트를 build함
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss # (8) action은 기존의 Momentjs를 지원하므로 동일한 포맷을 사용함
          utcOffset: "+09:00"  # (9) UTC기준 +9시간이 한국시간 KST가 된다.

      # 배포를 위해 필요한 파일들을 모아서 deploy 폴더에 넣고 그 폴더를 .zip파일로 압축함
      - name: Generate deployment package # (1)
        run: |
          mkdir -p bjpost/deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

      # 앞에서 만든 deploy.zip 파일을 EB에 올림
      - name: Deploy to EB # (2)
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} # 우리가 Secret 키로 설정한 값들
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: bjpost-application # Beanstalk에서 생성한 애플리케이션의 이름
          environment_name: Bjpost-application-env # Beanstalk에서 생성한 환경의 이름
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: bjpost/deploy/deploy.zip